apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tests
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
{{- range $path, $_ := .Files.Glob "tests/*.spec.js" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
